version: "2"
services:
  lint:
    image: buildkite/plugin-linter
    command: ["--id", "ailohq/github-status"]
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
