name: GitHub Status API
description: Creates GitHub status before/after a Buildkite step is executed.
author: https://github.com/ailohq
requirements: []
configuration:
  properties:
    username-env:
      type: string
    token-env:
      type: string
    target_url:
      type: string
    description:
      type: string
    context:
      type: string
  additionalProperties: false
