#!/bin/sh

set -euo pipefail

USERNAME=$(printenv ${BUILDKITE_PLUGIN_GITHUB_STATUS_USERNAME_ENV:-"GITHUB_USERNAME"})
TOKEN=$(printenv ${BUILDKITE_PLUGIN_GITHUB_STATUS_TOKEN_ENV:-"GITHUB_TOKEN"})
REPO_ORG=$(basename $(dirname $BUILDKITE_REPO) | sed 's/git@github.com://')
REPO_NAME=$(basename $BUILDKITE_REPO .git)

STATE=$(if [[ $BUILDKITE_COMMAND_EXIT_STATUS == "0" ]]; then echo success; else echo failure; fi)
TARGET_URL=${BUILDKITE_PLUGIN_GITHUB_STATUS_TARGET_URL:-""}
DESCRIPTION=${BUILDKITE_PLUGIN_GITHUB_STATUS_DESCRIPTION:-""}
CONTEXT=${BUILDKITE_PLUGIN_GITHUB_STATUS_CONTEXT:-""}

curl \
  -X POST \
  -u $USERNAME:$TOKEN \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/$REPO_ORG/$REPO_NAME/statuses/$BUILDKITE_COMMIT \
  -d "{\
    \"state\":\"$STATE\",\
    \"target_url\":\"$TARGET_URL\",\
    \"description\":\"$DESCRIPTION\",\
    \"context\":\"$CONTEXT\"\
  }"