#!/bin/sh

set -euo pipefail

# Curl that will return non-zero exit code,
# but still return its' response if it fails.
# ( https://superuser.com/a/1641410/215321 )
curlf() {
  OUTPUT_FILE=$(mktemp)
  HTTP_CODE=$(curl --silent --output $OUTPUT_FILE --write-out "%{http_code}" "$@")
  if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]] ; then
    >&2 cat $OUTPUT_FILE
    exit 22
  fi
  cat $OUTPUT_FILE
  rm $OUTPUT_FILE
}

USERNAME=$(printenv ${BUILDKITE_PLUGIN_GITHUB_STATUS_USERNAME_ENV:-"GITHUB_USERNAME"})
TOKEN=$(printenv ${BUILDKITE_PLUGIN_GITHUB_STATUS_TOKEN_ENV:-"GITHUB_TOKEN"})
REPO_ORG=$(basename $(dirname $BUILDKITE_REPO) | sed 's/git@github.com://')
REPO_NAME=$(basename $BUILDKITE_REPO .git)

STATE=pending
TARGET_URL=${BUILDKITE_PLUGIN_GITHUB_STATUS_TARGET_URL:-""}
DESCRIPTION=${BUILDKITE_PLUGIN_GITHUB_STATUS_DESCRIPTION:-""}
CONTEXT=${BUILDKITE_PLUGIN_GITHUB_STATUS_CONTEXT:-""}

curlf \
  -X POST \
  -u $USERNAME:$TOKEN \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/$REPO_ORG/$REPO_NAME/statuses/$BUILDKITE_COMMIT \
  -d "{\
    \"state\":\"$STATE\",\
    \"target_url\":\"$TARGET_URL\",\
    \"description\":\"$DESCRIPTION\",\
    \"context\":\"$CONTEXT\"\
  }"